/**
 * Created by Dimitri Aguera on 15/09/2017.
 */
const ADMIN_ROLE = 'ADMIN_ROLE';
const USER_ROLE = 'USER_ROLE';
const INVIT_ROLE = 'INVIT_ROLE';
const DEFAULT_AUTH_ROLE = 'USER_ROLE';
const MARC_ROLE = 'MARC_ROLE';

module.exports = {
    ADMIN_ROLE: ADMIN_ROLE,
    USER_ROLE: USER_ROLE,
    INVIT_ROLE: INVIT_ROLE,
    MARC_ROLE: MARC_ROLE,
    DEFAULT_AUTH_ROLE: DEFAULT_AUTH_ROLE,
    ALL_ROLE: [ADMIN_ROLE, USER_ROLE, INVIT_ROLE, MARC_ROLE],
};